### ISSUE TITLE
Enhancement: allow vector of starting values for `r` parameters, and r=0

### ISSUE THREAD

**Issue by alexpkeil1** [jenfb/bkmr#12]
Currently, the starting.values parameter in `kmbayes` will only use a single, positive starting value for r parameters, such that the starting value for every r value is the same. This prevents continuing a chain from the last completed values (e.g. when running a long simulation only to find that you don't have enough iterations, there is no way to restart from the final values of the chain). This would be helpful for using automatic stopping rules based on periodically running diagnostics, which could simplify the user experience.

When specifying initial values, It would be nice to be able to specify full parameter vectors and to be able to use all valid parameter values (including r=0 when varsel=TRUE).

**Comment by jenfb** [comment]
Thank you for letting me know about this issue. Please check out the updates to the functions, and let me know if they address the problem.

**Comment by alexpkeil1** [comment]
Looks good!
