### ISSUE TITLE
kmbayes expects starting values of h.hat > 0

### ISSUE THREAD

**Issue by alexpkeil1** [jenfb/bkmr#13]
When setting initial values, the kmbayes function expects initial values of h.hat to be > 0, but I don't see a reason for that constraint (it looks like a copy/paste error?). The thrown error is as follows

    starting.values$h.hat > 0 are not all TRUE

It doesn't look like these values get over-written, so initial values show up in the posterior distribution (this is disruptive if trying to start a new fit from the final iteration in a previous fit).

**Comment by jenfb** [comment]
Thanks for pointing out this unnecessary restriction. I have updated the code to no longer throw an error for starting values that are not positive. Let me know if this works now, and if you find any other similar issues.

**Comment by alexpkeil1** [comment]
Great - seems to work as designed and didn't cause any issues that I saw. I've incorporated this as bkmrhat::kmbayes_continue, which can start a new MCMC chain from the last values of a prior kmbayes fit and combines them into an object that inherits from "bkmrfit" objects. 
```
   devtools::install_github("alexpkeil1/bkmrhat")
   library(bkmrhat) # must be version 0.3.8+
   
   set.seed(111)
   dat <- bkmr::SimData(n = 50, M = 5, ind=1:3, Zgen="realistic")
   y <- dat$y
   Z <- dat$Z
   X <- cbind(dat$X, rnorm(50))
   
   # run 10 initial iterations for a model with only 2 exposures
   Z2 = Z
   kmfitbma.start <- suppressWarnings(bkmr::kmbayes(y = y, Z = Z2, X = X, iter = 10, verbose = FALSE, varsel = TRUE, est.h = TRUE))
   
   # run 20 additional iterations
   moreiterations = suppressWarnings(kmbayes_continue(kmfitbma.start, iter=20))
   res = kmbayes_diag(moreiterations)
   summary(res)
```
