### ISSUE TITLE
Error in PredictorResponseUnivar

### ISSUE THREAD

**Issue by JennicaZhao** [jenfb/bkmr#16]
When I run the PredictorResponseUnivar it gave the following warning:  
`data_frame()` is deprecated as of tibble 1.1.0.
Please use `tibble()` instead.
This warning is displayed once every 8 hours.
Call `lifecycle::last_warnings()` to see where this warning was generated.`select_()` is deprecated as of dplyr 0.7.0.
Please use `select()` instead.
This warning is displayed once every 8 hours.
Call `lifecycle::last_warnings()` to see where this warning was generated.

Could you please let me know why am I getting this warning?
Thanks!

**Comment by jenfb** [comment]
This issue has been addressed in the latest version of the software now available on CRAN.
