### ISSUE TITLE
Warning in ComputePostmeanHnew.approx and ComputePostmeanHnew.exact

### ISSUE THREAD

**Issue by paujedynak** [jenfb/bkmr#17]
UPDATE: while trying to make a pull request I realized that the bug is fixed in the GitHub repo version (0.2.0.9000), however the latest version downloadable from CRAN (0.2.0) does not contain this update yet.

For R >= 4.0 calling class(Znew) == "data.frame" may return FALSE FALSE (for "matrix" "array") which triggers warnings 
Warning message:
In if (class(Znew) == "data.frame") Znew <- data.matrix(Znew) :
  the condition has length > 1 and only the first element will be used

Not lethal but annoying :)

To be replaced by inherits(Znew, "data.frame")

**Comment by jenfb** [comment]
This issue has been addressed in the latest version of the software now available on CRAN.
