### ISSUE TITLE
Using function SingVarRiskSummaries or PredictorResponseBivarLevels with binomial outcome

### ISSUE THREAD

**Issue by xiaokang-lucy** [jenfb/bkmr#18]
I'm confused whether can bkmr's function  SingVarRiskSummaries or PredictorResponseBivarLevels be used for analysing binomial outcome. For example, if I want to describe the association between environmental pollutants and hypertention(binomial), whether SingVarRiskSummaries or PredictorResponseBivarLevels is applicable?
  Thank you very much!

**Comment by jenfb** [comment]
You could still use those functions but the interpretation is different. Take a look at the 2018 paper and companion code (linked in README file).

**Comment by xiaokang-lucy** [comment]
Thank you very much for your response. That really helped.



At 2022-03-05 02:25:16, "Jennifer F. Bobb" ***@***.***> wrote:

You could still use those functions but the interpretation is different. Take a look at the 2018 paper and companion code (linked in README file).

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
