### ISSUE TITLE
How Can I fited a spline in the X part of BKMR model?

### ISSUE THREAD

**Issue by minato1990** [jenfb/bkmr#20]
I am confused when one of the adjustements  (Xi) had nolinear effect. In classic GLM, we can fitted a spline for the covaribale to adjust its nolinear effect, but I can not find some solution in your current version. Is there some change in codes for the spline?

**Comment by jenfb** [comment]
You can specify the X matrix manually to allow for nonlinear relationships. For example, here is how you could use a natural cubic spline basis with 3 degrees of freedom to adjust for the variable x nonlinearly:

library(splines)
x <- rnorm(100, 0, 1)
spl <- ns(x, 3)
X <- as.matrix(spl)
