### ISSUE TITLE
Maximum number of exposure and sample size

### ISSUE THREAD

**Issue by jianvhuang** [jenfb/bkmr#22]
Hi, in the publication _Statistical software for analyzing the health effects of multiple concurrent exposures via Bayesian kernel machine regression_  published on _Environmental Health_ , you simulated a dataset that included 30 exposure variables for a sample size of n = 200. 

I wonder if you have tested an even larger number of exposure variables? And how is the performance of BKMR at different combination of number of exposure and sample size?

Specifically for my analysis, I have 65 exposures in ~100 individuals.

**Comment by jenfb** [comment]
I have not tested a larger number of exposures but think it could still work OK given the shrinkage when using the variable selection option. It would definitely be a good idea to run simulations in those larger number of exposure settings though to see the impact.
