### ISSUE TITLE
Error in kmbayes with knots

### ISSUE THREAD

**Issue by fan918235** [jenfb/bkmr#24]
Hi-
I had the following error when running kmbayes() function with knots:
> set.seed(111)
> fitkm_111 <- kmbayes(Y_arthritis, Z = scale_Z_expo, X = X_cor, 
+                      iter = 1000, verbose = FALSE, varsel = TRUE, 
+                      groups=c(1,2,2,2,2,3,4,5,6,7,8,7,2,9,10,11), 
+                      family = "binomial", est.h = TRUE, knots=knot50)
Fitting probit regression model
Iteration: 100 (10% completed; 7.44703 mins elapsed)
Iteration: 200 (20% completed; 15.47211 mins elapsed)
Iteration: 300 (30% completed; 24.33769 mins elapsed)
Iteration: 400 (40% completed; 33.35945 mins elapsed)
Iteration: 500 (50% completed; 42.25391 mins elapsed)
Iteration: 600 (60% completed; 51.09813 mins elapsed)
Iteration: 700 (70% completed; 59.93684 mins elapsed)
Iteration: 800 (80% completed; 1.14526 hours elapsed)
Iteration: 900 (90% completed; 1.2912 hours elapsed)
Iteration: 1000 (100% completed; 1.4403 hours elapsed)
**Warning message**:
In if (class(knots) != "matrix") knots <- as.matrix(knots) :
  the condition has length > 1 and only the first element will be used

Have you ever encountered similar trouble? Looking forward to your valuable answer.

**Comment by jenfb** [comment]
This issue has been addressed in the latest version of the software now available on CRAN.
